"""first commit

Revision ID: 789c805b4be2
Revises: 
Create Date: 2024-12-02 02:47:27.659345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789c805b4be2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_uri', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('digest_status', sa.Boolean(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('human_raw_response_id', sa.UUID(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_raw_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('message_event_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('machine_curation_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('human_curation_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('digest_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('human_raw_response')
    op.drop_table('curated_file')
    # ### end Alembic commands ###
