"""modify name 

Revision ID: b8ecd572499a
Revises: bdacd8539ca4
Create Date: 2024-12-02 03:41:14.583151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ecd572499a'
down_revision: Union[str, None] = 'bdacd8539ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curated_file', 'digest_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curated_file', 'digest_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
